apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-container-pvc
  namespace: benchmark
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Ti
  storageClassName: rook-ceph-block
