kind: ConfigMap
apiVersion: v1
metadata:
  name: fio-seqread-job-config
data:
  seqread-job.fio: |-
    [global]
    ioengine=libaio
    iodepth=32
    direct=1
    invalidate=1
    runtime=120
    numjobs=4
    size=1g
    [seq-read]
    bs=128k
    rw=read
    time_based
    group_reporting
    stonewall
