kind: ConfigMap
apiVersion: v1
metadata:
  name: fio-randread-job-config
data:
  randread-job.fio: |-
    [global]
    ioengine=libaio
    iodepth=64
    direct=1
    invalidate=1
    runtime=120
    numjobs=4
    size=1g
    [randread]
    bs=64k
    rw=randread
    time_based
    group_reporting
    stonewall
